--1
DECLARE EXTERNAL FUNCTION FACTORIAL
INTEGER
RETURNS
INTEGER BY VALUE
ENTRY_POINT 'factorial' MODULE_NAME 'libfuncs';

--2
DECLARE EXTERNAL FUNCTION PMT
DOUBLE PRECISION, INTEGER, DOUBLE PRECISION
RETURNS DOUBLE PRECISION BY VALUE
ENTRY_POINT'pmt' MODULE_NAME 'libfuncs';

--3
DECLARE EXTERNAL FUNCTION BIN2DEC
 CSTRING(255)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'bin2dec' MODULE_NAME 'libfuncs';

--4
DECLARE EXTERNAL FUNCTION DEC2BIN	
INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT 'dec2bin' MODULE_NAME 'libfuncs';

--5
DECLARE EXTERNAL FUNCTION HEX2DEC	
CSTRING(255)
RETURNS INTEGER by value
ENTRY_POINT 'hex2dec' MODULE_NAME 'libfuncs';

--6
DECLARE EXTERNAL FUNCTION DEC2HEX	
INTEGER
RETURNS CSTRING(25)
ENTRY_POINT 'dec2hex' MODULE_NAME 'libfuncs';

--7
DECLARE EXTERNAL FUNCTION COMPARE_STRING	
CSTRING(255), CSTRING(255)
RETURNS INTEGER by value
ENTRY_POINT 'compare_string' MODULE_NAME 'libfuncs';

--8
DECLARE EXTERNAL FUNCTION TRIM2
CSTRING(25), CSTRING(1)
RETURNS CSTRING(25)
ENTRY_POINT 'trim' MODULE_NAME 'libfuncs';

--9
DECLARE EXTERNAL FUNCTION REPEAT
CSTRING(50), INTEGER
RETURNS CSTRING(50)
ENTRY_POINT 'repeat' MODULE_NAME 'libfuncs';

--10
DECLARE EXTERNAL FUNCTION Ping
CSTRING(255)
RETURNS integer by value
ENTRY_POINT 'ping' MODULE_NAME 'libfuncs';


DECLARE EXTERNAL FUNCTION F2C	
DOUBLE PRECISION
RETURNS DOUBLE PRECISION by value
ENTRY_POINT 'f2c' MODULE_NAME 'libfuncs';


DECLARE EXTERNAL FUNCTION C2F	
DOUBLE PRECISION
RETURNS DOUBLE PRECISION by value
ENTRY_POINT 'c2f' MODULE_NAME 'libfuncs';